AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Prefix:
    Type: String
  Environment:
    Type: String
    AllowedValues:
      - production
  Region:
    Type: String
    Default: ap-northeast-1
  SGStackName:
    Type: String
  VPCStackName:
    Type: String
  AMIImageId:
    Type: String
  KeyName:
    Type: String

Resources:
  EC2InstanceA:
    Type: AWS::EC2::Instance
    Properties:
      ImageId:
        Ref: AMIImageId
      KeyName:
        Ref: KeyName
      InstanceType: t2.micro
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          SubnetId:
            Fn::ImportValue:
              Fn::Join: ["-", [Ref: VPCStackName, "PublicSubnetA"]]
          GroupSet:
            - Fn::ImportValue:
                Fn::Join: ["-", [Ref: SGStackName, ApplicationSecurityGroup]]
      UserData:
        Fn::Base64: |
          #!/bin/bash
          sudo yum update -y
          sudo yum install -y httpd
          sudo systemctl start httpd.service
          sudo systemctl enable httpd.service
          echo "Hello world! from EC2 instance A" > /var/www/html/index.html
      Tags:
        - Key: Name
          Value:
            Fn::Join: ["-", [Ref: Prefix, Ref: Environment, "EC2InstanceA"]]

  EC2InstanceC:
    Type: AWS::EC2::Instance
    Properties:
      ImageId:
        Ref: AMIImageId
      KeyName:
        Ref: KeyName
      InstanceType: t2.micro
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          SubnetId:
            Fn::ImportValue:
              Fn::Join: ["-", [Ref: VPCStackName, "PublicSubnetC"]]
          GroupSet:
            - Fn::ImportValue:
                Fn::Join: ["-", [Ref: SGStackName, ApplicationSecurityGroup]]
      UserData:
        Fn::Base64: |
          #!/bin/bash
          sudo yum update -y
          sudo yum install -y httpd
          sudo systemctl start httpd.service
          sudo systemctl enable httpd.service
          echo "Hello world! from EC2 instance C" > /var/www/html/index.html
      Tags:
        - Key: Name
          Value:
            Fn::Join: ["-", [Ref: Prefix, Ref: Environment, "EC2InstanceC"]]
Outputs:
  EC2InstanceA:
    Value:
      Ref: EC2InstanceA
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-EC2InstanceA"

  EC2InstanceC:
    Value:
      Ref: EC2InstanceC
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-EC2InstanceC"
